eureka:
  client:
    service-url:
      defaultZone: http://dream96.top:8761/eureka/    # http://eureka2:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false #FIXME true
spring:
  application:
    name: eureka
server:
  port: 8761