eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false #FIXME true
spring:
  application:
    name: eureka
server:
  port: 8762